apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-super-new
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: sbus-secret
      key:  connectionstring
auth:
  secretStore: kubernetes
scopes:
  - tpaperorders
  - tpaperdeliver